
server:
  port: 9098

spring:
  application:
    name: spring_learn
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB



#  datasource:
#    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource


#此配置解决swagger Failed to start bean 'documentationPluginsBootstrapper'的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# thymeleaf
  thymeleaf:
#缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
#开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML
    resources:
      static-locations: classpath:/static/
    mvc:
      static-path-pattern: /static/**
# mybatis-plus配置
mybatis-plus:
  mapper-locations:
    classpath:mapper/**/*Mapper.xml,classpath:mapper/*Mapper.xml
# Mybatis返回Map类型,单数据库字段值为空时,不显示字段问题配置,true:显示值为空的字段
  configuration:
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
